# Generated by Django 4.2.7 on 2023-12-19 17:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('country_code', models.CharField(default='+966', max_length=5)),
                ('phone', models.CharField(max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=9)])),
                ('wallet', models.FloatField(default=0)),
                ('income', models.IntegerField(null=True)),
                ('income_source', models.CharField(max_length=15, null=True)),
                ('marital_status', models.CharField(max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('utilized', models.BooleanField(default=False)),
                ('expirey', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
