# Generated by Django 4.2.7 on 2023-12-10 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=9, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=9)])),
                ('wallet', models.FloatField(default=0)),
                ('income', models.IntegerField(null=True)),
                ('income_source', models.CharField(max_length=15, null=True)),
                ('marital_status', models.CharField(max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
