# Generated by Django 4.2.7 on 2023-12-01 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('country_code', models.CharField(choices=[('SA +966', 'SA +966')], default='SA +966', max_length=10, null=True)),
                ('phone', models.CharField(max_length=9, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=9)])),
                ('wallet', models.IntegerField(null=True)),
                ('income', models.IntegerField(null=True)),
                ('income_source', models.CharField(choices=[('job', 'Job'), ('freelancer', 'Freelancer'), ('other', 'Other')], default='job', max_length=15, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widower', 'Widower'), ('divorced', 'Divorced')], default='single', max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
