# Generated by Django 4.2.7 on 2023-12-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(default='SA +966', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='income_source',
            field=models.CharField(default='job', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(default='single', max_length=15, null=True),
        ),
    ]
