# Generated by Django 4.2.7 on 2023-12-18 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_amount', models.IntegerField()),
                ('shipped', models.BooleanField(default=False)),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.coupon')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.store'),
        ),
    ]
